### PR TITLE
Fix #344

### LINKED ISSUE #344: Fails to build on `x86_64-unknown-netbsd`
```
$ git checkout 5.0.0-pre.11
Previous HEAD position was 43ea645 Add missing comma in "As used by:" list
HEAD is now at 71c57b4 Prepare 5.0.0-pre.11
$ cargo build --target x86_64-unknown-netbsd
Updating crates.io index
   Compiling kqueue-sys v1.0.2
error[E0308]: mismatched types
  --> ~/.cargo/registry/src/github.com-1ecc6299db9ec823/kqueue-sys-1.0.2/src/lib.rs:68:20
   |
68 |             udata: ptr::null_mut(),
   |                    ^^^^^^^^^^^^^^^ expected `isize`, found *-ptr
   |
   = note:     expected type `isize`
           found raw pointer `*mut _`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0308`.
error: could not compile `kqueue-sys`

To learn more, run the command again with --verbose.
```

Spotted in https://github.com/rust-lang/rust/pull/87719#issuecomment-891625996.

### PR DESCRIPTION
**Pull request by 0xpr03**
Pin new fixed version

### CODE REVIEW

**Comment by 0xpr03** [comment]
The only thing I'd like to add is a a test case for this

**Comment by lnicola** [comment]
You could try to add a cargo check job for the netbsd target.

**Comment by lnicola** [comment]
Actually this should be 1.0.4. kqueue is a step ahead of kqueue-sys.

**Comment by 0xpr03** [comment]
Oh yeah, good catch. So I guess my build still succeeded because we're using kqueue-sys 1.0.3 underneath.

**Comment by 0xpr03** [comment]
Fixed in 2286a8ee7694dcf672a4128d3d9dd4f6c8f1456f

**Comment by lnicola** [comment]
Looks good, thanks!

**Pull request merged**
