### PR TITLE
Update URLs

### PR DESCRIPTION
**Pull request by atouchet**

### CODE REVIEW

**Comment by 0xpr03** [comment]
Thanks!

**Comment by atouchet** [comment]
Perhaps the Travis CI URLs shouldn't have been changed. https://travis-ci.org/notify-rs/notify says " We couldn't find the repository". What is the Travis URL supposed to be in the new org?

**Comment by passcod** [comment]
oh, it should be .com

**Comment by atouchet** [comment]
Ah, that works. I opened #220 to update a few more links.

**Pull request merged**
