### PR TITLE
chore(deps): update crossbeam-channel to 5.0

### PR DESCRIPTION
**Pull request by Plecra**

### CODE REVIEW

**Comment by JohnTitor** [comment]
I don't think we could accept this as it will break our MSRV.

**Comment by 0xpr03** [comment]
@Plecra do you have a requirement to use a newer crossbeam-channel ?

**Comment by Plecra** [comment]
Ah, bummer. I can close the PR if this just isn't suitable for `notify`, but maybe a new version release is a good time to make an MSRV bump? I've seen a lot of crates moving to 1.36.

I just spotted this when reviewing [bevy](https://github.com/bevyengine/bevy)'s duplicate dependencies. I can't speak for the project, but this would work towards https://github.com/bevyengine/bevy/pull/667 (`notify` is the only external crate that's using crossbeam-channel).

**Comment by 0xpr03** [comment]
I think we can do this for 0.5, as its still in preview.

**Comment by JohnTitor** [comment]
Then it's fine to me as well. But we should tweak CI to make it green, and mention MSRV on the changelog since we'd like to treat it as a breaking change.

**Comment by cart** [comment]
Let me know if theres anything I can do to help with getting this upgraded / releasing the next notify version. I'm invested in cleaning up Bevy's dep tree :smile:

**Pull request closed without merging**
