### PR TITLE
Update changelog about maintainers

### PR DESCRIPTION
**Pull request by JohnTitor**
Suggested in https://github.com/notify-rs/notify/pull/222#issuecomment-537213120

### CODE REVIEW

**Comment by JohnTitor** [comment]
Failed in installing windows-sdk, is it needed nowadays? I tested on my fork, the CI was passed without it.
CC: @passcod

**Comment by passcod** [comment]
Yeah, not sure. It seems to be a temporary failure on Travis CI, given it was working two days ago. You could try removing it and see

**Comment by JohnTitor** [comment]
Yes, the failure is temporary and the fix is a stopgap but it's worth to remove the installation if it isn't needed. I'll try to do.

**Comment by JohnTitor** [comment]
Opened #225

**Pull request merged**
