### PR TITLE
Backport some updates and bump version to 4.0.15

### PR DESCRIPTION
**Pull request by atouchet**

### CODE REVIEW

**Comment by atouchet** [comment]
Hrmm, still failing. I'm not sure exactly what the issue is here. If a maintainer would like to take this over feel free.

**Comment by 0xpr03** [comment]
Thanks for the PR, I followed your changes, but I think some tests weren't working in the first place. I'll see to that.
CC @JohnTitor

**Comment by JohnTitor** [comment]
Sorry for the delay! I think #236 should make v4 branch green and the failure on macOS is random so we can ignore that.

**Comment by 0xpr03** [comment]
@JohnTitor do you want to merge/rebase this ? Otherwise ping me if I haven't done this on Monday.

**Comment by JohnTitor** [comment]
The change looks good, I'd like to see the check suite with rebase.

**Comment by 0xpr03** [comment]
I restartet [the build](https://travis-ci.com/notify-rs/notify/builds/138162203).

**Comment by JohnTitor** [comment]
Thanks!

**Pull request merged**
