### PR TITLE
Remove abandoned description on README

### LINKED ISSUE #221: Update README description of abandoned
This crate is looking for maintainers and we have some maintainers now.
It'd be nice to have the description for looking for maintainers instead of the abandoned description on README.

### PR DESCRIPTION
**Pull request by JohnTitor**
Closes #221

### CODE REVIEW

**Comment by 0xpr03** [comment]
We also may want to remove the sponsoring button. CC @passcod

**Comment by Dylan-DPC** [comment]
I think we have enough maintainers on the team already that we don't need to state in the readme. We can leave the issue open if you want in case anyone else pops up in future. 

Also +1 on the sponsorship if passcod is fine with it, don't want to end up having to face the "who get's sponsored?" question

**Comment by JohnTitor** [comment]
Remove description for looking for maintainers.
If @passcod wants to remove the sponsor button, I'd like to submit another PR.

**Comment by passcod** [comment]
Yes absolutely remove it. I really should have done so upon committing the notice, it was ambiguous/irresponsible in hindsight to leave it

**Comment by passcod** [comment]
Also the changelog should mark the organisational change from me to y'all

**Comment by JohnTitor** [comment]
Should we do it with this pull request or another pull request?

**Comment by dhiemaz** [comment]
I think this PR is about to remove abandoned description, so for removing maintainers should be do with another PR. wdyt @passcod, @Dylan-DPC

**Comment by passcod** [comment]
I don't mind either way, but new PR would free this one to land without more delay I think

**Comment by JohnTitor** [comment]
So, could we merge this now?

**Comment by Dylan-DPC** [comment]
Yes. Let's merge this. Otherwise someone would come up with another change and we'll be stuck for a long time 😂

**Pull request merged**
