### PR TITLE
Run rustfmt

### PR DESCRIPTION
**Pull request by JohnTitor**

### CODE REVIEW

**Comment by dhiemaz** [comment]
> _No description provided._

@JohnTitor what is this changes is about ?

**Comment by JohnTitor** [comment]
@dhiemaz run `cargo fmt` to format code

**Comment by 0xpr03** [comment]
We may want to enforce rust fmt checking during CI

**Comment by dhiemaz** [comment]
> We may want to enforce rust fmt checking during CI

That would be better @0xpr03, any other concern @Dylan-DPC , @passcod ?

**Comment by passcod** [comment]
My experience is generally that running style checking during CI is a deterrent for contributions. While it's not super easy with Travis (but I think there's a ready-made recipe for github actions somewhere), having something auto-commit the result of rustfmt onto PRs (or at merge time) is a lot friendlier.

**Comment by JohnTitor** [comment]
Running rustfmt on CI check is hard work a bit for any contributors even though it keeps code style always. I prefer to submit PR for rustfmt sometimes rather than asking contributors to run rustfmt often.

**Comment by JohnTitor** [comment]
Anyway, I'm going to merge this. If we still want to run rustfmt on CI, please open an issue.

**Pull request merged**
